version: '3.8'

services:
  web:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: .env

  api:
    build: ./backend
    ports:
      - "4000:4000"
    env_file: .env
    depends_on:
      - db

  ai-service:
    build: ./ai-service
    ports:
      - "5000:5000"
    env_file: .env

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: