services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "${WEB_PORT:-3000}:3000"
    env_file: .env
    depends_on:
      - api
      - ai-service

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "${API_PORT:-4000}:4000"
    env_file: .env
    depends_on:
      - db

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile.ai
    ports:
      - "${AI_PORT:-5000}:5000"
    env_file: .env
    depends_on:
      - api

  db:
    image: postgres:14
    secrets:
      - db_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

secrets:
  db_password:
    file: ./db_password.txt

volumes:
  pgdata:
